name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.13
  - dask
  - aiohttp
  - requests
  - pytest
  - pyarrow
  - awkward
  - dask-histogram
  - uproot
  - hist
